assistant:
  name: "Personal AI Assistant"
  version: "1.0.0"
  max_tokens: 2000
  temperature: 0.7
  # AI Provider: 'openai' or 'lmstudio'
  ai_provider: "lmstudio"  # Switch to lmstudio by default

# AI Provider configurations
ai_providers:
  openai:
    model: "gpt-3.5-turbo"
    max_tokens: 2000
    temperature: 0.7
  
  lmstudio:
    base_url: "http://localhost:1234/v1"  # Default LM Studio endpoint
    model: "local-model"  # Will be auto-detected from LM Studio
    max_tokens: 300  # Increased for meaningful responses
    temperature: 0.3  # Balanced for better content
    timeout: 15  # Increased slightly for longer responses

integrations:
  gmail:
    enabled: true
    max_emails: 50
    cache_duration: 300  # 5 minutes
  
  calendar:
    enabled: true
    days_ahead: 7
    cache_duration: 300
  
  github:
    enabled: true
    max_repos: 10
    cache_duration: 600  # 10 minutes
  
  trello:
    enabled: false
    cache_duration: 600

ui:
  theme: "dark"
  show_icons: true
  max_lines: 20

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/assistant.log" 