assistant:
  name: "Personal AI Assistant"
  version: "1.0.0"
  max_tokens: 2000
  temperature: 0.7

integrations:
  gmail:
    enabled: true
    max_emails: 50
    cache_duration: 300  # 5 minutes
  
  calendar:
    enabled: true
    days_ahead: 7
    cache_duration: 300
  
  github:
    enabled: true
    max_repos: 10
    cache_duration: 600  # 10 minutes
  
  trello:
    enabled: false
    cache_duration: 600

ui:
  theme: "dark"
  show_icons: true
  max_lines: 20

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/assistant.log" 